# Generated by Django 3.0.4 on 2020-04-05 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True, verbose_name='nom')),
                ('picture', models.URLField(verbose_name='image')),
            ],
            options={
                'verbose_name': 'categorie',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='nom')),
                ('category_tags1', models.CharField(max_length=250, verbose_name='category_tags1')),
                ('category_tags2', models.CharField(max_length=600, verbose_name='category_tags2')),
                ('nutri_score', models.CharField(max_length=3, verbose_name='nutri_score')),
                ('repere_fat100g', models.CharField(max_length=3)),
                ('repere_saturatedfat100g', models.CharField(max_length=3)),
                ('repere_sugars100g', models.CharField(max_length=3)),
                ('repere_saltunit', models.CharField(max_length=3)),
                ('picture', models.URLField(null=True, verbose_name='image')),
                ('url', models.CharField(max_length=150, verbose_name='lien')),
                ('stores', models.CharField(max_length=250, verbose_name='magasin')),
                ('category', models.ManyToManyField(to='pbeurre.Category')),
            ],
            options={
                'verbose_name': 'aliment',
                'verbose_name_plural': 'aliments',
            },
        ),
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.ManyToManyField(to='pbeurre.Food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'favori',
                'verbose_name_plural': 'favoris',
            },
        ),
    ]
