language: python
jobs:
  include:              
  - name: 'Python 3.6'
  - python: "3.6"  

branches:
  only:
    - master

env: DJANGO_SETTINGS_MODULE=plateforme_project.settings.travis

dist: xenial
services:
  - xvfb

before_script:
  - pip install -r requirements.txt
  - set ENV = chromedriver.exe


addons:
  chrome: stable
  
services:
  - postgresql

script:
   - python manage.py test
   
