language: python
python:
  - '3.6'

branches:
  only:
    - master

before_script:
  - pip install -r requirements.txt

services:
  - postgresql

env: DJANGO_SETTINGS_MODULE=plateforme_project.settings.travis

script:
  - ./manage.py test
