language: python
python:
  - '3.6'
  - '3.5'

before_script:
  - pip install -r requirements.txt
  
services:
  - postgresql

env: DJANGO_SETTINGS_MODULE="purbeurre.travis_settings"

script:
  - mkdir purbeurre/static
  - yes yes | purbeurre/manage.py collectstatic
  - purbeurre/manage.py test website