language: python
jobs:
  include:              
  - name: 'Python 3.6'
  - python: "3.6"  

branches:
  only:
    - master

env: DJANGO_SETTINGS_MODULE=plateforme_project.settings.travis

before_script:
  - pip install -r requirements.txt
  - set ENV = chromedriver.exe

addons:
  chrome: stable

services:
  - postgresql

script:
   - python manage.py test
   
install:
   - wget -N https://chromedriver.storage.googleapis.com/85.0.4183.38/chromedriver_linux64.zip -P ~/
   - unzip ~/chromedriver_linux64.zip -d ~/
   - rm ~/chromedriver_linux64.zip
   - sudo mv -f ~/chromedriver /stanb/local/share/
   - sudo chmod +x /stanb/local/share/chromedriver
   - sudo ln -s /stanb/local/share/chromedriver /stanb/local/bin/chromedriver