language: python
python:
  - '3.6'
  include:
    - python: 3.6
    os: Windows
    language: shell

branches:
  only:
    - master

before_script:
  - pip install -r requirements.txt
  - set ENV = chromedriver.exe

services:
  - postgresql                                             
                                              
env: DJANGO_SETTINGS_MODULE=plateforme_project.settings.travis

script:
   - python manage.py test
