language: python
jobs:
  include:              
  - name: 'Python 3.6 on Windows'
  - python: "3.6"  
    os: Windows

branches:
  only:
    - master

env: DJANGO_SETTINGS_MODULE=plateforme_project.settings.travis

before_script:
  - pip install -r requirements.txt
  - set ENV = chromedriver.exe

services:
  - postgresql
  - xvfb


script:
   - python manage.py test