language: python
python:
        -'3.5'

before_script:
        - pip install -r requirements.txt

branches:
  only:
        - master

env: DJANGO_SETTINGS_MODULE='plateforme_project.settings.travis'

services:
        - postgresql

script:
        - python manage.py test

 
