language: python
python:
  - '3.6'

branches:
  only:
    - master

before_script:
  - pip install -r requirements.txt
  - pip install webdriver-manager
  - set ENV = chromedriver.exe

services:
  - postgresql

env: DJANGO_SETTINGS_MODULE=plateforme_project.settings.travis

script:
  - python manage.py test



os: windows

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - oracle-java8-set-default


