language: python
python:
  - '3.6'

branches:
  only:
    - master

before_script:
  - pip install -r requirements.txt
  - pip install webdriver-manager
services:
  - postgresql

env: DJANGO_SETTINGS_MODULE=plateforme_project.settings.travis

script:
  - python manage.py test

sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - oracle-java8-set-default


