build: trusty
language: python
jobs:
  include:              
  - name: 'Python 3.6'
  - python: "3.6"  

branches:
  only:
    - master

env: DJANGO_SETTINGS_MODULE=plateforme_project.settings.travis

dist: xenial

before_script:
  - echo $PATH
  - wget -N https://chromedriver.storage.googleapis.com/84.0.4147.30/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - export CHROME_BIN=chromium-browser
  - pip install -r requirements.txt

addons:
  chrome: stable
  
services:
  - postgresql
  - xvfb

script:
   - python manage.py test
   