#!/usr/bin/env python
# -*- coding: utf-  8 -*-


categories = []
urls_list = []
categories_id = []
category_name = []
count_product = []
name_list = [
    "Pâtes à tartiner au chocolat",
    "Barres de céréales",
    "Viandes fraîches",
    "Pains spéciaux",
    "Gâteaux et pâtisseries surgelés",
    "Fromages à tartiner",
    "Jus de fruits à base de concentré",
    "Veloutés de légumes",
    "Bonbons gélifiés",
    "Sodas au cola",
    "Yaourts brassés",
    "Boudins",
    "Sauces pour pâtes",
    "Crèmes",
    "Chips de pommes de terre à l'huile de tournesol",
    "Boissons lactées",
    "Boissons instantanées",
    "Saumons fumés",
    "Légumes frais",
    "Eaux de sources",
    "Pâtes de blé dur",
    "Mélanges de flocons de céréales",
    "Jambons secs",
    "Escalopes de dinde",
    "Crèmes glacées en pot",
    "Plats au porc",
    "Crêpes et galettes",
    "Pâtés végétaux",
    "Fromages à pâte fraîche",
    "Sardines à l'huile",
    "Aides culinaires",
    "Cookies",
    "Légumes surgelés",
    "Vins rouges",
    "Produits artisanaux",
    "Rillettes de viande",
    "Desserts au chocolat",
    "Fromages au lait cru",
    "Pains d'épices",
    "Laits demi-écrémés",
    "Laits homogénéisés",
    "Nouilles",
    "Foies gras entiers",
    "Yaourts natures",
    "Fromages de chèvre",
    "Laits UHT",
    "Confitures de fraises",
    "Légumes-feuilles",
    "Eaux minérales",
    "Barres chocolatées",
    "Plats à base de riz",
    "Crè",
    "Pains de mie",
    "Rillettes de poissons"
]
